# Vibe Trader 配置文件

# 交易配置
trading:
  # 交易对列表 (目前仅支持 BTC)
  symbols:
    - BTCUSDT
  
  # 数据采集时间框架
  timeframes:
    short_term: 3m      # 短期时间框架 (3分钟)
    long_term: 4h       # 长期时间框架 (4小时)
  
  # 数据窗口大小
  data_windows:
    short_term_limit: 100   # 短期K线数量
    long_term_limit: 100    # 长期K线数量
  
  # 调度间隔 (秒)
  schedule_interval: 180    # 每3分钟执行一次

# 币安 API 配置
binance:
  api_key_env: BINANCE_API_KEY
  api_secret_env: BINANCE_API_SECRET
  base_url: https://fapi.binance.com  # U本位永续合约
  testnet: false  # 是否使用测试网

# Deepseek API 配置
deepseek:
  api_key_env: DEEPSEEK_API_KEY
  base_url: https://api.deepseek.com
  model: deepseek-reasoner
  max_tokens: 4000
  temperature: 1.0

# 执行平台配置
execution:
  platform: binance  # 可选: binance, hype, aster, papertrading
  # 是否启用模拟交易模式
  paper_trading: true

# 风险控制配置
risk_management:
  # 最大单笔订单占账户价值百分比
  max_position_size_pct: 0.20
  
  # 最大持仓数量
  max_open_positions: 3
  
  # 最低决策置信度阈值
  min_confidence: 0.75
  
  # 允许交易的币种白名单
  allowed_symbols:
    - BTCUSDT
    - ETHUSDT
  
  # 最大价格滑点百分比
  max_price_slippage_pct: 0.02

# 日志配置
logging:
  level: INFO
  log_file: logs/vibe_trader.log
  max_bytes: 10485760  # 10MB
  backup_count: 5

# 状态持久化配置
state:
  state_file: data/state.json
  backup_enabled: true

